name: 'Scope Import'
author: 'Daniel Rodriguez <@drodriguezhdez> | UndefinedLabs'
description: 'Import your test reports to Scope'
inputs:
  dsn:
    description: 'Scope DSN'
    required: true
  path:
    description: 'Path to test reports folder'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'