name: 'Scope for Junit'
author: 'Daniel Rodriguez <@drodriguezhdez> | UndefinedLabs'
description: 'Import your JUnit XML reports to Scope'
inputs:
  dsn:
    description: 'Scope DSN'
    required: true
  path:
    description: 'Path to JUnit XML reports folder'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'